import type { ClubIntroAsset, ExhibitData, PresentationCue, PresentationGroup } from './types';

export const CLUB_INTRO_ASSETS: ClubIntroAsset[] = [
  {
    id: 'ti-smedley',
    kind: 'photo',
    title: 'Ralph C. Smedley',
    role: 'toastmasters-scale',
    aspect: 606 / 663,
    localPath: '/assets/club-intro/ti-smedley.png',
    caption: 'Ralph C. Smedley, founder of Toastmasters.',
  },
  {
    id: 'ti-ymca-building',
    kind: 'photo',
    title: 'YMCA roots',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-ymca-building.png',
    caption: 'The YMCA setting where the early Toastmasters idea took shape.',
  },
  {
    id: 'ti-1924-club-meeting',
    kind: 'photo',
    title: '1924 club meeting',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-1924-club-meeting.png',
    caption: 'An early Toastmasters club meeting scene.',
  },
  {
    id: 'ti-world-map',
    kind: 'photo',
    title: 'Toastmasters around the world',
    role: 'toastmasters-scale',
    aspect: 1672 / 941,
    localPath: '/assets/club-intro/ti-world-map.png',
    caption: 'Toastmasters has clubs across a global learning network.',
  },
  {
    id: 'ti-network-audience',
    kind: 'photo',
    title: 'People gathered to learn',
    role: 'network',
    aspect: 1.778,
    sourceUrl: 'https://unsplash.com/photos/EVgsAbL51Rk',
    localPath: '/assets/club-intro/ti-network-audience.jpg',
    caption: 'A real room of people gathered around a shared learning experience.',
    credit: 'Unsplash',
  },
  {
    id: 'ti-first-impression',
    kind: 'photo',
    title: 'First Impression',
    role: 'public-speaking',
    aspect: 941 / 1672,
    localPath: '/assets/club-intro/ti-first-impression.png',
    caption: 'A stage moment where a first impression matters.',
  },
  {
    id: 'ti-2025-winners',
    kind: 'photo',
    title: '2025 winners',
    role: 'public-speaking',
    aspect: 1000 / 663,
    localPath: '/assets/club-intro/ti-2025-winners.jpg',
    caption: 'Speech contests and recognition turn practice into public achievement.',
  },
  {
    id: 'ti-leadership-meeting',
    kind: 'photo',
    title: 'Leadership through responsibility',
    role: 'leadership',
    aspect: 1.5,
    sourceUrl: 'https://unsplash.com/photos/TcvZEb8cSJI',
    localPath: '/assets/club-intro/ti-leadership-meeting.jpg',
    caption: 'Leadership shows up in real teams, meetings, and shared decisions.',
    credit: 'Unsplash',
  },
  {
    id: 'network-member-day',
    kind: 'poster',
    title: 'Member Day connections',
    role: 'network',
    aspect: 0.563,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/6fe004c1-1891-4e1e-9ea8-069f0226069b/media/1000046777.jpg',
    localPath: '/assets/club-intro/member-day.jpg',
    meetingTheme: 'SoarHigh Member Day',
    caption: 'Members and guests meet through SoarHigh activities.',
  },
  {
    id: 'speaking-workshop',
    kind: 'photo',
    title: 'Learning by doing',
    role: 'public-speaking',
    aspect: 0.75,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047516.jpg',
    localPath: '/assets/club-intro/public-speaking-workshop.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'Members practise speaking, facilitation, and prepared sharing.',
  },
  {
    id: 'speaking-debate',
    kind: 'photo',
    title: 'Debate Arena',
    role: 'public-speaking',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047519.jpg',
    localPath: '/assets/club-intro/debate-arena.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'A live format for fast, clear, persuasive communication.',
  },
  {
    id: 'leadership-election',
    kind: 'photo',
    title: 'Club officers election',
    role: 'leadership',
    aspect: 2.17,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/7eaad288-10b1-475a-b82b-8fb0c8122511/media/1000047084.jpg',
    localPath: '/assets/club-intro/officer-election.jpg',
    meetingNo: 457,
    meetingTheme: '23rd Club Officers Election',
    caption: 'Club officers learn leadership by organizing real meetings.',
  },
  {
    id: 'soarhigh-ai-poster',
    kind: 'poster',
    title: 'A recent SoarHigh meeting',
    role: 'soarhigh-history',
    aspect: 0.562,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047095.jpg',
    localPath: '/assets/club-intro/ai-poster.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'A recent English meeting poster from the SoarHigh website.',
  },
  {
    id: 'family-group',
    kind: 'photo',
    title: 'Family atmosphere',
    role: 'family',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047522.jpg',
    localPath: '/assets/club-intro/family-group.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'A warm community where members support each other.',
  },
  {
    id: 'fun-halloween',
    kind: 'photo',
    title: 'Halloween special meeting',
    role: 'fun',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/5cd74e63-4b9d-4c51-8a66-a2e90696ebf4/media/1000037798.jpg',
    localPath: '/assets/club-intro/halloween.jpg',
    meetingTheme: 'Halloween Trick Treat Toast',
    caption: 'SoarHigh has hosted many special themed meetings.',
  },
  {
    id: 'fun-christmas',
    kind: 'poster',
    title: 'Christmas dinner party',
    role: 'fun',
    aspect: 0.749,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/ce0a4299-b5de-4ed3-aa13-bb03ade5dff7/media/1000040992.jpg',
    localPath: '/assets/club-intro/christmas.jpg',
    meetingTheme: 'Christmas Eve Dinner Party',
    caption: 'Events outside the regular meeting keep the club lively.',
  },
  {
    id: 'growth-evaluation',
    kind: 'photo',
    title: 'Evaluation workshop',
    role: 'growth',
    aspect: 0.75,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/7dbf1542-b26d-4fb5-889f-19feb2bebeb8/media/1000045464.jpg',
    localPath: '/assets/club-intro/evaluation-workshop.png',
    meetingNo: 452,
    meetingTheme: 'Power Up Your Evaluation',
    caption: 'Growth happens through practice, feedback, and another try.',
  },
  {
    id: 'soarhigh-link',
    kind: 'qr',
    title: 'soarhigh.top',
    role: 'final-cta',
    caption: 'Website, mini app, and meeting archive.',
  },
];

export const CLUB_INTRO_ASSET_MAP = new Map(
  CLUB_INTRO_ASSETS.map(asset => [asset.id, asset] as const),
);

export const CLUB_INTRO_EXHIBITS: ExhibitData[] = [
  {
    id: 'ti-history-smedley',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Ralph C. Smedley',
    desc: 'Ralph C. Smedley founded Toastmasters and shaped its early learning culture.',
    x: 5.25,
    y: 2.42,
    width: 2.4,
    height: 2.6,
    assetIds: ['ti-smedley'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-ymca',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'YMCA Roots',
    desc: 'The YMCA setting where the early Toastmasters idea took shape.',
    x: 1.05,
    y: 3.36,
    width: 3.05,
    height: 1.45,
    rotationZ: 0.02,
    assetIds: ['ti-ymca-building'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-1924-meeting',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: '1924 Club Meeting',
    desc: 'An early Toastmasters club meeting scene.',
    x: 0.55,
    y: 1.42,
    width: 3.15,
    height: 1.45,
    rotationZ: -0.017,
    assetIds: ['ti-1924-club-meeting'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-world-map-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Global Toastmasters Network',
    desc: 'Toastmasters clubs connect members across more than 140 countries.',
    x: -4.15,
    y: 2.5,
    width: 4.05,
    height: 2.28,
    assetIds: ['ti-world-map'],
    lines: ['140+ countries', '15k+ clubs', '280k+ members', '90+ Shenzhen clubs'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-key-network',
    kind: 'keyword',
    roomIdx: 0,
    wall: 'left',
    title: 'Network',
    desc: 'A wide club network creates chances to connect with people from different walks of life.',
    z: 2.4,
    y: 2.35,
    width: 3.55,
    height: 2.35,
    assetIds: ['ti-network-audience'],
    lines: ['Connect', 'All walks of life', 'Opportunities'],
    accent: '#0582ca',
  },
  {
    id: 'ti-speaking-first-impression',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: 'First Impression',
    desc: 'A stage moment where a first impression matters.',
    z: -2.75,
    y: 2.52,
    width: 1.72,
    height: 2.94,
    assetIds: ['ti-first-impression'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-speaking-2025-winners',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: '2025 Winners',
    desc: 'Speech contests and recognition turn practice into public achievement.',
    z: 1.84,
    y: 2.52,
    width: 3.55,
    height: 2.46,
    assetIds: ['ti-2025-winners'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-key-leadership',
    kind: 'keyword',
    roomIdx: 0,
    wall: 'back',
    title: 'Leadership',
    desc: 'By serving in officer teams and meeting roles, members build leadership through real responsibility.',
    x: -4.25,
    y: 2.35,
    width: 3.55,
    height: 2.35,
    assetIds: ['ti-leadership-meeting'],
    lines: ['Organize', 'Serve', 'Lead'],
    accent: '#8e44ad',
  },
  {
    id: 'ti-ambient-community',
    kind: 'photo',
    roomIdx: 0,
    wall: 'back',
    title: 'Global Community',
    desc: 'A supporting gallery photo for Toastmasters as a worldwide learning community.',
    x: 4.15,
    y: 2.25,
    width: 2.2,
    height: 1.48,
    assetIds: ['ti-network-audience'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history',
    kind: 'timeline',
    roomIdx: 1,
    wall: 'left',
    title: 'SoarHigh History',
    desc: 'From Shenzhen Airline corporate club to public English-speaking club.',
    z: 0.75,
    y: 2.35,
    width: 3.9,
    height: 2.35,
    assetIds: ['leadership-election'],
    lines: ['2014 Shenzhen Airline Corporate Club', '2016 Public Club', '2024 100% English Speaking Club', "Bao'an English-speaking Club"],
    accent: '#ff8a2a',
  },
  {
    id: 'soarhigh-ambient-debate',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Debate Practice',
    desc: 'A supporting SoarHigh photo showing members practising ideas in the room.',
    z: -3.45,
    y: 2.25,
    width: 2.15,
    height: 1.6,
    assetIds: ['speaking-debate'],
    accent: '#2ec4b6',
    showPlaque: false,
  },
  {
    id: 'soarhigh-ambient-party',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Club Event Moment',
    desc: 'A supporting SoarHigh photo for the club as an active community.',
    z: 4.55,
    y: 2.25,
    width: 2.15,
    height: 1.6,
    assetIds: ['fun-halloween'],
    accent: '#ef476f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-slogan',
    kind: 'slogan',
    roomIdx: 1,
    wall: 'back',
    title: 'Soarhigh So High',
    desc: 'Take me fly!',
    x: -3.3,
    y: 3.1,
    width: 5.2,
    height: 1.25,
    lines: ['Soarhigh So High', 'Take Me Fly'],
    accent: '#ffd166',
  },
  {
    id: 'soarhigh-family',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'right',
    title: 'Family Atmosphere',
    desc: 'More than Toastmasters: a family to love, care, laugh, and inspire.',
    z: -4.15,
    y: 2.25,
    width: 3.45,
    height: 2.35,
    assetIds: ['family-group'],
    lines: ['Love', 'Care', 'Laugh', 'Inspire'],
    accent: '#4f7bd9',
  },
  {
    id: 'soarhigh-fun',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'right',
    title: 'Fun Events',
    desc: 'Outings, theme nights, parties, and creative special meetings keep the club alive.',
    z: -0.25,
    y: 2.25,
    width: 3.45,
    height: 2.35,
    assetIds: ['fun-halloween'],
    lines: ['Outings', 'Halloween', 'Christmas', 'Special meetings'],
    accent: '#ef476f',
  },
  {
    id: 'soarhigh-christmas-party',
    kind: 'photo',
    roomIdx: 1,
    wall: 'right',
    title: 'Christmas Party',
    desc: 'Theme meetings and parties make SoarHigh feel lively and memorable.',
    z: 2.1,
    y: 2.25,
    width: 1.6,
    height: 2.65,
    assetIds: ['fun-christmas'],
    accent: '#ef476f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-growth',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'front',
    title: 'Growth',
    desc: 'SoarHigh is a stage to test imperfect ideas, see real changes, and feel the happiness from growth.',
    x: 4.15,
    y: 2.25,
    width: 2.45,
    height: 3.0,
    assetIds: ['speaking-workshop'],
    lines: ['Try', 'Feedback', 'Change', 'Grow'],
    accent: '#2ec4b6',
  },
  {
    id: 'soarhigh-ambient-evaluation',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Feedback and Evaluation',
    desc: 'A supporting SoarHigh photo about learning through feedback.',
    x: -4.15,
    y: 2.25,
    width: 2.05,
    height: 2.7,
    assetIds: ['growth-evaluation'],
    accent: '#ffd166',
    showPlaque: false,
  },
  {
    id: 'soarhigh-cta',
    kind: 'qr',
    roomIdx: 1,
    wall: 'back',
    title: 'Visit SoarHigh',
    desc: 'Website: soarhigh.top. Mini app: 搜嗨头马.',
    x: 4.25,
    y: 2.35,
    width: 3.2,
    height: 2.0,
    assetIds: ['soarhigh-link'],
    lines: ['www.soarhigh.top', 'Mini app: 搜嗨头马', 'Photos, posts, meetings'],
    accent: '#2bb673',
  },
];

export const CLUB_INTRO_EXHIBIT_MAP = new Map(
  CLUB_INTRO_EXHIBITS.map(exhibit => [exhibit.id, exhibit] as const),
);

export const CLUB_INTRO_PRESENTATION_GROUPS: PresentationGroup[] = [
  {
    id: 'ti-speaking-wall',
    title: 'Toastmasters Meeting and Stage',
    roomIdx: 0,
    exhibitIds: [
      'ti-speaking-first-impression',
      'ti-speaking-2025-winners',
    ],
  },
  {
    id: 'ti-history-wall',
    title: 'Toastmasters History and Scale',
    roomIdx: 0,
    exhibitIds: [
      'ti-history-smedley',
      'ti-history-ymca',
      'ti-history-1924-meeting',
      'ti-world-map-wall',
    ],
  },
];

export const CLUB_INTRO_PRESENTATION_CUES: PresentationCue[] = [
  {
    id: 'ti-meeting-scene',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Toastmasters Meeting',
    desc: 'This is a common Toastmasters meeting scene: speaking, listening, and evaluation inside a structured, supportive room.',
    descSegments: [
      {text: 'A common Toastmasters meeting scene:'},
      {text: 'Speaking', tone: 'accent', bullet: true},
      {text: 'Listening', tone: 'accent', bullet: true},
      {text: 'Evaluation', tone: 'accent', bullet: true, breakAfter: true},
      {text: 'inside a ', breakAfter: false},
      {text: 'structured, supportive room', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'This is a common Toastmasters meeting scene. Members come together to practise speaking, listening, and giving evaluations in a structured, supportive room.',
    camera: {
      position: [3.72, 1.68, -7.35],
      lookAt: [8.5, 2.5, -7.75],
      durationMs: 1100,
    },
    transition: 'group-start',
  },
  {
    id: 'ti-nonprofit-purpose',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Nonprofit for Growth',
    desc: 'Toastmasters is a nonprofit organization that helps members improve public speaking, communication, and leadership through practice.',
    descSegments: [
      {text: 'A '},
      {text: 'nonprofit organization', tone: 'strong'},
      {text: ' helping members improve:'},
      {text: 'Public speaking', tone: 'accent', bullet: true},
      {text: 'Communication', tone: 'accent', bullet: true},
      {text: 'Leadership', tone: 'accent', bullet: true, breakAfter: true},
      {text: ' through '},
      {text: 'practice', tone: 'italic'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is a nonprofit organization that helps its members improve public speaking, communication, and leadership skills through practice.',
    camera: {
      position: [3.72, 1.7, -6.9],
      lookAt: [8.5, 2.45, -7.45],
      durationMs: 650,
    },
    transition: 'group-slide',
  },
  {
    id: 'ti-contest-stage',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-2025-winners',
    title: 'Practice Becomes Stage',
    desc: 'Toastmasters also has speech contests. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    descSegments: [
      {text: 'Toastmasters also has '},
      {text: 'speech contests', tone: 'accent'},
      {text: '.'},
      {text: '2025 winners', tone: 'stat', bullet: true},
      {text: 'Regular practice grows into a ', bullet: true},
      {text: 'larger stage', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is also a stage for contests and recognition. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    camera: {
      position: [3.86, 1.72, -4.55],
      lookAt: [8.5, 2.42, -3.16],
      durationMs: 900,
    },
    transition: 'group-slide',
  },
  {
    id: 'ti-smedley-origin',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-smedley',
    title: 'Where It Began',
    desc: 'Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    descSegments: [
      {text: 'More than ', bullet: true},
      {text: '100 years', tone: 'stat'},
      {text: ' of history'},
      {text: 'Founded by ', bullet: true},
      {text: 'Ralph C. Smedley', tone: 'warm'},
      {text: 'Founded in ', bullet: true},
      {text: '1924', tone: 'stat'},
    ],
    spokenCue: 'You may wonder where Toastmasters came from. Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    camera: {
      position: [3.35, 1.72, -2.45],
      lookAt: [5.25, 2.42, 1.0],
      durationMs: 1250,
    },
    transition: 'group-switch',
  },
  {
    id: 'ti-ymca-roots',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-ymca',
    title: 'The Early Home',
    desc: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    descSegments: [
      {text: 'The early idea took shape in a '},
      {text: 'YMCA setting', tone: 'warm'},
      {text: '.'},
      {text: 'People gathered to practise ', bullet: true},
      {text: 'better communication', tone: 'accent'},
      {text: '.'},
    ],
    spokenCue: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    camera: {
      position: [1.0, 1.72, -2.15],
      lookAt: [1.05, 3.22, 1.0],
      durationMs: 850,
    },
    transition: 'group-slide',
  },
  {
    id: 'ti-early-meeting',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-1924-meeting',
    title: 'Early Club Meetings',
    desc: 'From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    descSegments: [
      {text: 'A simple learning model from the beginning:'},
      {text: 'Speak', tone: 'accent', bullet: true},
      {text: 'Listen', tone: 'accent', bullet: true},
      {text: 'Evaluate', tone: 'accent', bullet: true},
      {text: 'Try again', tone: 'italic', bullet: true},
    ],
    spokenCue: 'This is an early club meeting scene. From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    camera: {
      position: [0.65, 1.58, -2.05],
      lookAt: [0.55, 1.45, 1.0],
      durationMs: 750,
    },
    transition: 'group-slide',
  },
  {
    id: 'ti-global-scale',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-world-map-wall',
    title: 'A Global Network',
    desc: 'Today, Toastmasters has clubs in 140+ countries, with 15K+ clubs and 280K+ members. In Shenzhen, there are 90+ clubs.',
    descSegments: [
      {text: 'Today, Toastmasters reaches:'},
      {text: '140+ countries', tone: 'stat', bullet: true},
      {text: '15K+ clubs', tone: 'stat', bullet: true},
      {text: '280K+ members', tone: 'stat', bullet: true},
      {text: '90+ clubs in Shenzhen', tone: 'warm', bullet: true},
    ],
    spokenCue: 'Today, Toastmasters has clubs in more than 140 countries, with more than 15 thousand clubs and 280 thousand members. Just in Shenzhen, there are more than 90 clubs.',
    camera: {
      position: [-3.35, 1.7, -2.55],
      lookAt: [-4.15, 2.45, 1.0],
      durationMs: 950,
    },
    transition: 'group-slide',
  },
];
