import type { ClubIntroAsset, ExhibitData, PresentationCue, PresentationGroup } from './types';

export const CLUB_INTRO_ASSETS: ClubIntroAsset[] = [
  {
    id: 'ti-smedley',
    kind: 'photo',
    title: 'Ralph C. Smedley',
    role: 'toastmasters-scale',
    aspect: 606 / 663,
    localPath: '/assets/club-intro/ti-smedley.png',
    caption: 'Ralph C. Smedley, founder of Toastmasters.',
  },
  {
    id: 'ti-ymca-building',
    kind: 'photo',
    title: 'YMCA roots',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-ymca-building.png',
    caption: 'The YMCA setting where the early Toastmasters idea took shape.',
  },
  {
    id: 'ti-1924-club-meeting',
    kind: 'photo',
    title: '1924 club meeting',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-1924-club-meeting.png',
    caption: 'An early Toastmasters club meeting scene.',
  },
  {
    id: 'ti-world-map',
    kind: 'photo',
    title: 'Toastmasters around the world',
    role: 'toastmasters-scale',
    aspect: 1672 / 941,
    localPath: '/assets/club-intro/ti-world-map.png',
    caption: 'Toastmasters has clubs across a global learning network.',
  },
  {
    id: 'ti-past-international-presidents',
    kind: 'photo',
    title: 'Past International Presidents',
    role: 'toastmasters-scale',
    aspect: 1000 / 663,
    localPath: '/assets/club-intro/ti-past-international-presidents.png',
    caption: "Past Toastmasters International presidents gathered in 2024 to celebrate Toastmasters' 100th anniversary.",
  },
  {
    id: 'ti-networking',
    kind: 'photo',
    title: 'Networking',
    role: 'network',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/ti-networking.jpg',
    caption: 'Members expand opportunities by connecting across a wider learning network.',
  },
  {
    id: 'ti-public-speaking',
    kind: 'photo',
    title: 'Public Speaking',
    role: 'public-speaking',
    aspect: 1,
    localPath: '/assets/club-intro/ti-public-speaking.jpg',
    caption: 'Practice in front of an audience turns communication into confidence.',
  },
  {
    id: 'ti-leadership',
    kind: 'photo',
    title: 'Leadership',
    role: 'leadership',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/ti-leadership.jpg',
    caption: 'Club roles and shared responsibility give members practical leadership experience.',
  },
  {
    id: 'ti-first-impression',
    kind: 'photo',
    title: 'First Impression',
    role: 'public-speaking',
    aspect: 941 / 1672,
    localPath: '/assets/club-intro/ti-first-impression.png',
    caption: 'A stage moment where a first impression matters.',
  },
  {
    id: 'ti-2025-winners',
    kind: 'photo',
    title: '2025 winners',
    role: 'public-speaking',
    aspect: 1000 / 663,
    localPath: '/assets/club-intro/ti-2025-winners.jpg',
    caption: 'Speech contests and recognition turn practice into public achievement.',
  },
  {
    id: 'ti-2026-118-guangfo',
    kind: 'photo',
    title: '2026 District 118 Guangzhou-Foshan Summit',
    role: 'network',
    aspect: 2000 / 1125,
    localPath: '/assets/club-intro/ti-2026-118-guangfo.jpg',
    caption: 'A moment from the 2026 District 118 Guangzhou-Foshan summit.',
  },
  {
    id: 'soarhigh-shenzhen-airline',
    kind: 'photo',
    title: 'Shenzhen Airline',
    role: 'soarhigh-history',
    aspect: 4846 / 3231,
    localPath: '/assets/club-intro/shenzhen-airline.jpeg',
    caption: 'SoarHigh was established by Shenzhen Airline in 2014 as a corporate club.',
  },
  {
    id: 'soarhigh-meeting-04',
    kind: 'photo',
    title: 'Meeting #4',
    role: 'soarhigh-history',
    aspect: 839 / 462,
    localPath: '/assets/club-intro/meeting-04.jpg',
    meetingNo: 4,
    caption: 'An early SoarHigh club meeting.',
  },
  {
    id: 'soarhigh-meeting-07',
    kind: 'photo',
    title: 'Meeting #7',
    role: 'soarhigh-history',
    aspect: 697 / 442,
    localPath: '/assets/club-intro/meeting-07.jpg',
    meetingNo: 7,
    caption: 'Another early SoarHigh club meeting as the club grew.',
  },
  {
    id: 'soarhigh-2024-full-english',
    kind: 'photo',
    title: 'Full English Club',
    role: 'soarhigh-history',
    aspect: 1620 / 1080,
    localPath: '/assets/club-intro/2024-full-english.jpg',
    meetingTheme: 'Full English Speaking Club',
    caption: 'In 2024, SoarHigh decided to become a full English-speaking club.',
  },
  {
    id: 'soarhigh-family-1',
    kind: 'photo',
    title: 'Family Atmosphere',
    role: 'family',
    aspect: 4624 / 3472,
    localPath: '/assets/club-intro/family-1.jpeg',
    caption: 'SoarHigh members sharing a warm family moment.',
  },
  {
    id: 'soarhigh-family-2',
    kind: 'photo',
    title: 'Family Care',
    role: 'family',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/family-2.jpg',
    caption: 'A SoarHigh family moment with members together.',
  },
  {
    id: 'soarhigh-family-3',
    kind: 'photo',
    title: 'Family Laugh',
    role: 'family',
    aspect: 1279 / 1706,
    localPath: '/assets/club-intro/family-3.jpg',
    caption: 'A vertical family photo from SoarHigh.',
  },
  {
    id: 'soarhigh-family-4',
    kind: 'photo',
    title: 'Family Inspire',
    role: 'family',
    aspect: 1707 / 1280,
    localPath: '/assets/club-intro/family-4.jpg',
    caption: 'SoarHigh members together as a club family.',
  },
  {
    id: 'soarhigh-fun-1',
    kind: 'photo',
    title: 'Fun Moment 1',
    role: 'fun',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/fun-1.jpeg',
    caption: 'A SoarHigh fun event moment.',
  },
  {
    id: 'soarhigh-fun-2',
    kind: 'photo',
    title: 'Fun Moment 2',
    role: 'fun',
    aspect: 4624 / 3472,
    localPath: '/assets/club-intro/fun-2.jpeg',
    caption: 'Members enjoying a SoarHigh activity.',
  },
  {
    id: 'soarhigh-fun-3',
    kind: 'photo',
    title: 'Fun Moment 3',
    role: 'fun',
    aspect: 4624 / 3472,
    localPath: '/assets/club-intro/fun-3.jpeg',
    caption: 'A playful SoarHigh meeting or event moment.',
  },
  {
    id: 'soarhigh-fun-4',
    kind: 'photo',
    title: 'Fun Moment 4',
    role: 'fun',
    aspect: 1707 / 1280,
    localPath: '/assets/club-intro/fun-4.jpg',
    caption: 'A special SoarHigh activity with members together.',
  },
  {
    id: 'soarhigh-fun-5',
    kind: 'photo',
    title: 'Fun Moment 5',
    role: 'fun',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/fun-5.jpg',
    caption: 'A fun SoarHigh gathering.',
  },
  {
    id: 'soarhigh-fun-6',
    kind: 'photo',
    title: 'Fun Moment 6',
    role: 'fun',
    aspect: 1279 / 1706,
    localPath: '/assets/club-intro/fun-6.jpg',
    caption: 'A vertical SoarHigh fun event photo.',
  },
  {
    id: 'soarhigh-fun-7',
    kind: 'photo',
    title: 'Fun Moment 7',
    role: 'fun',
    aspect: 2275 / 1279,
    localPath: '/assets/club-intro/fun-7.jpeg',
    caption: 'A wide SoarHigh event moment.',
  },
  {
    id: 'soarhigh-fun-8',
    kind: 'photo',
    title: 'Fun Moment 8',
    role: 'fun',
    aspect: 1702 / 1276,
    localPath: '/assets/club-intro/fun-8.jpg',
    caption: 'A SoarHigh fun meeting scene.',
  },
  {
    id: 'soarhigh-growth-1',
    kind: 'photo',
    title: '2026 Contest Achievement',
    role: 'growth',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/growth-1.jpg',
    caption: 'SoarHigh members won 2026 Central Division contest awards.',
  },
  {
    id: 'meeting-458-guest-introduction',
    kind: 'photo',
    title: 'Guest Introduction',
    role: 'ordinary-photo',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047522.jpg',
    localPath: '/assets/club-intro/meeting-458-guest-introduction.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'Guest Introduction group photo.',
  },
  {
    id: 'meeting-455-about-childhood',
    kind: 'photo',
    title: 'About Childhood',
    role: 'ordinary-photo',
    aspect: 1702 / 1276,
    localPath: '/assets/club-intro/meeting-455-about-childhood.jpg',
    meetingNo: 455,
    meetingTheme: 'About Childhood',
    caption: 'A photo from this meeting.',
  },
  {
    id: 'poster-459',
    kind: 'poster',
    title: 'Meeting #459 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2276,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/c3b77884-0fbe-4654-b98a-6ca5b1a480cb/media/1000047523.jpg',
    localPath: '/assets/club-intro/poster-459.jpg',
    meetingNo: 459,
    meetingTheme: 'Colors to Calm Our Minds',
    caption: 'Colors to Calm Our Minds',
  },
  {
    id: 'poster-458',
    kind: 'poster',
    title: 'Meeting #458 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2276,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047095.jpg',
    localPath: '/assets/club-intro/poster-458.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'AI Boom or AI Doom',
  },
  {
    id: 'poster-456',
    kind: 'poster',
    title: 'Meeting #456 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2276,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/15c86d9e-2231-4bff-a0d5-d6ad904554de/media/1000046311.jpg',
    localPath: '/assets/club-intro/poster-456.jpg',
    meetingNo: 456,
    meetingTheme: 'The Charm Of Sports',
    caption: 'The Charm Of Sports',
  },
  {
    id: 'poster-454',
    kind: 'poster',
    title: 'Meeting #454 Poster',
    role: 'ordinary-photo',
    aspect: 935 / 1683,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/b18fbb84-0fa5-4519-af66-d8f9ba1e97f9/media/1000045653.jpg',
    localPath: '/assets/club-intro/poster-454.jpg',
    meetingNo: 454,
    meetingTheme: 'Fall in Love with Your Own Script',
    caption: 'Fall in Love with Your Own Script',
  },
  {
    id: 'poster-447',
    kind: 'poster',
    title: 'Meeting #447 Poster',
    role: 'ordinary-photo',
    aspect: 1279 / 2275,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/1e2ab383-83f2-4811-9b4f-84d6440e04f1/media/1000044150.jpg',
    localPath: '/assets/club-intro/poster-447.jpg',
    meetingNo: 447,
    meetingTheme: 'LOVE & THE CITY - Dating & Relationships in Shenzhen',
    caption: 'LOVE & THE CITY - Dating & Relationships in Shenzhen',
  },
  {
    id: 'poster-441',
    kind: 'poster',
    title: 'Meeting #441 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2276,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/a0e60274-6607-4fbc-8eb3-d2f60462eadd/media/1000042266.jpg',
    localPath: '/assets/club-intro/poster-441.jpg',
    meetingNo: 441,
    meetingTheme: 'Sharing Your Life Stories',
    caption: 'Sharing Your Life Stories',
  },
  {
    id: 'poster-440',
    kind: 'poster',
    title: 'Meeting #440 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2276,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/1648521a-edec-4d36-9915-73c8d725e673/media/1000042023.jpg',
    localPath: '/assets/club-intro/poster-440.jpg',
    meetingNo: 440,
    meetingTheme: 'Warm Connections: Imagine, Then Soar',
    caption: 'Warm Connections: Imagine, Then Soar',
  },
  {
    id: 'poster-427',
    kind: 'poster',
    title: 'Meeting #427 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2280,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/b9038abe-ef8a-466b-ad5f-42e68c8d3a0a/media/1000037506.jpg',
    localPath: '/assets/club-intro/poster-427.jpg',
    meetingNo: 427,
    meetingTheme: 'Deep connections',
    caption: 'Deep connections',
  },
  {
    id: 'poster-428',
    kind: 'poster',
    title: 'Meeting #428 Poster',
    role: 'ordinary-photo',
    aspect: 1280 / 2281,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/5cd74e63-4b9d-4c51-8a66-a2e90696ebf4/media/1000037507.jpg',
    localPath: '/assets/club-intro/poster-428.jpg',
    meetingNo: 428,
    meetingTheme: 'Trick, Treat, Toast',
    caption: 'Trick, Treat, Toast',
  },
  {
    id: 'soarhigh-link',
    kind: 'qr',
    title: 'soarhigh.top',
    role: 'final-cta',
    caption: 'Website, mini app, and meeting archive.',
  },
];

export const CLUB_INTRO_ASSET_MAP = new Map(
  CLUB_INTRO_ASSETS.map(asset => [asset.id, asset] as const),
);

export const CLUB_INTRO_EXHIBITS: ExhibitData[] = [
  {
    id: 'ti-history-smedley',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Ralph C. Smedley',
    desc: 'Ralph C. Smedley founded Toastmasters and shaped its early learning culture.',
    x: 5.25,
    y: 2.42,
    width: 2.4,
    height: 2.6,
    assetIds: ['ti-smedley'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-ymca',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'YMCA Roots',
    desc: 'The YMCA setting where the early Toastmasters idea took shape.',
    x: 1.05,
    y: 3.36,
    width: 3.05,
    height: 1.45,
    rotationZ: 0.02,
    assetIds: ['ti-ymca-building'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-1924-meeting',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: '1924 Club Meeting',
    desc: 'An early Toastmasters club meeting scene.',
    x: 0.55,
    y: 1.42,
    width: 3.15,
    height: 1.45,
    rotationZ: -0.017,
    assetIds: ['ti-1924-club-meeting'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-world-map-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Global Toastmasters Network',
    desc: 'Toastmasters clubs connect members across more than 140 countries.',
    x: -4.15,
    y: 2.5,
    width: 4.05,
    height: 2.28,
    assetIds: ['ti-world-map'],
    lines: ['140+ countries', '15k+ clubs', '280k+ members', '90+ Shenzhen clubs'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-network',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Network',
    desc: 'A huge club network gives members chances to connect with people from all walks of life.',
    z: 3.24,
    y: 2.4,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-networking'],
    accent: '#0582ca',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-public-speaking',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Public Speaking',
    desc: 'Members learn through practice to present and communicate with more confidence.',
    z: 0,
    y: 2.79,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-public-speaking'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-leadership',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Leadership',
    desc: 'Club officer roles and activities help members grow practical leadership skills.',
    z: -3.24,
    y: 2.45,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-leadership'],
    accent: '#8e44ad',
    showPlaque: false,
  },
  {
    id: 'ti-speaking-first-impression',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: 'First Impression',
    desc: 'A stage moment where a first impression matters.',
    z: -2.75,
    y: 2.52,
    width: 1.72,
    height: 2.94,
    assetIds: ['ti-first-impression'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-speaking-2025-winners',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: '2025 Winners',
    desc: 'Speech contests and recognition turn practice into public achievement.',
    z: 1.84,
    y: 2.52,
    width: 3.55,
    height: 2.46,
    assetIds: ['ti-2025-winners'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-2026-118-guangfo-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'back',
    title: '2026 District 118 Guangzhou-Foshan Summit',
    desc: 'A 2026 District 118 Guangzhou-Foshan summit moment.',
    x: -5.12,
    y: 2.35,
    width: 3.55,
    height: 2.1,
    assetIds: ['ti-2026-118-guangfo'],
    accent: '#c9a96e',
    showPlaque: false,
  },
  {
    id: 'ti-past-international-presidents-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'back',
    title: 'Past International Presidents',
    desc: "Past Toastmasters International presidents gathered in 2024 to celebrate Toastmasters' 100th anniversary.",
    x: 5.12,
    y: 2.36,
    width: 3.45,
    height: 2.25,
    assetIds: ['ti-past-international-presidents'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-airline',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Shenzhen Airline',
    desc: 'SoarHigh was established in 2014 by Shenzhen Airline as a corporate club.',
    z: 3.45,
    y: 2.32,
    width: 2.55,
    height: 1.7,
    assetIds: ['soarhigh-shenzhen-airline'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-meeting-04',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Meeting #4',
    desc: 'An early SoarHigh meeting from the first chapter of the club.',
    z: 0.15,
    y: 3.26,
    width: 2.31,
    height: 1.36,
    assetIds: ['soarhigh-meeting-04'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-meeting-07',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Meeting #7',
    desc: 'Another early SoarHigh meeting as the club community developed.',
    z: -0.15,
    y: 1.5,
    width: 2.03,
    height: 1.36,
    assetIds: ['soarhigh-meeting-07'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-full-english',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Full English Club',
    desc: "In 2024, SoarHigh decided to become a full English-speaking club and remains Bao'an district's only English-speaking club.",
    z: -3.45,
    y: 2.68,
    width: 2.55,
    height: 1.7,
    assetIds: ['soarhigh-2024-full-english'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-family-photo-1',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Family Atmosphere',
    desc: 'SoarHigh is more than Toastmasters: a family to love, care, laugh, and inspire.',
    x: -6.32,
    y: 3.6,
    width: 1.42,
    height: 1.06,
    rotationZ: -0.022,
    matInset: 0.045,
    presentationCueId: 'soarhigh-keyword-family-cue',
    assetIds: [
      'soarhigh-family-1',
      'soarhigh-family-2',
      'soarhigh-family-3',
      'soarhigh-family-4',
    ],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-family-photo-2',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Family Care',
    desc: 'A SoarHigh family moment with members together.',
    x: -3.96,
    y: 3.3,
    width: 1.42,
    height: 1.06,
    rotationZ: 0.026,
    matInset: 0.045,
    presentationCueId: 'soarhigh-keyword-family-cue',
    assetIds: ['soarhigh-family-2'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-family-photo-3',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Family Laugh',
    desc: 'A vertical family photo from SoarHigh.',
    x: -5.62,
    y: 2.02,
    width: 0.88,
    height: 1.18,
    rotationZ: 0.018,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-family-cue',
    assetIds: ['soarhigh-family-3'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-family-photo-4',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Family Inspire',
    desc: 'SoarHigh members together as a club family.',
    x: -3.94,
    y: 1.72,
    width: 1.42,
    height: 1.06,
    rotationZ: -0.022,
    matInset: 0.045,
    presentationCueId: 'soarhigh-keyword-family-cue',
    assetIds: ['soarhigh-family-4'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-1',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Fun Events',
    desc: 'SoarHigh hosts outings, special meetings, and playful events beyond regular club meetings.',
    x: -2.05,
    y: 3.55,
    width: 1.05,
    height: 0.79,
    rotationZ: -0.02,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: [
      'soarhigh-fun-1',
      'soarhigh-fun-2',
      'soarhigh-fun-3',
      'soarhigh-fun-4',
      'soarhigh-fun-5',
      'soarhigh-fun-6',
      'soarhigh-fun-7',
      'soarhigh-fun-8',
    ],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-2',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Fun Outings',
    desc: 'Members enjoy regular outings and activities together.',
    x: -0.57,
    y: 3.22,
    width: 1.05,
    height: 0.79,
    rotationZ: 0.024,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-2'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-3',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Special Meetings',
    desc: 'SoarHigh has hosted many special fun meetings.',
    x: 1.03,
    y: 3.6,
    width: 1.05,
    height: 0.79,
    rotationZ: -0.018,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-3'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-4',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Fun Gatherings',
    desc: 'A SoarHigh activity moment with members together.',
    x: 2.53,
    y: 3.28,
    width: 1.05,
    height: 0.79,
    rotationZ: 0.022,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-4'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-5',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Monthly Activities',
    desc: 'A fun SoarHigh gathering outside the usual meeting rhythm.',
    x: -1.93,
    y: 2.05,
    width: 1.05,
    height: 0.79,
    rotationZ: 0.018,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-5'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-6',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Playful Moments',
    desc: 'A vertical SoarHigh fun event photo.',
    x: -0.5,
    y: 1.78,
    width: 0.68,
    height: 0.9,
    rotationZ: -0.02,
    matInset: 0.03,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-6'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-7',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Fun Community',
    desc: 'A wide SoarHigh event moment.',
    x: 1.13,
    y: 2.13,
    width: 1.32,
    height: 0.74,
    rotationZ: 0.016,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-7'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-fun-photo-8',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Past Events',
    desc: 'A SoarHigh fun meeting scene.',
    x: 2.67,
    y: 1.78,
    width: 1.05,
    height: 0.79,
    rotationZ: -0.018,
    matInset: 0.035,
    presentationCueId: 'soarhigh-keyword-fun-cue',
    assetIds: ['soarhigh-fun-8'],
    accent: '#b87956',
    showPlaque: false,
  },
  {
    id: 'soarhigh-growth-contest-2026',
    kind: 'photo',
    roomIdx: 1,
    wall: 'back',
    title: 'Growth Through Contests',
    desc: 'In 2026, SoarHigh members won first place in the Central Division Prepared Speech Evaluation Contest and second place in the Central Division International Speech Contest.',
    x: 5.42,
    y: 2.62,
    width: 2.12,
    height: 1.58,
    rotationZ: 0.018,
    matInset: 0.055,
    presentationCueId: 'soarhigh-keyword-growth-cue',
    assetIds: ['soarhigh-growth-1'],
    accent: '#86a85c',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-459',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #459',
    desc: 'Colors to Calm Our Minds',
    x: 7.14,
    y: 4.04,
    width: 0.62,
    height: 1.03,
    rotationZ: -0.018,
    matInset: 0.03,
    assetIds: ['poster-459'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-458',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #458',
    desc: 'AI Boom or AI Doom',
    x: 5.36,
    y: 4.15,
    width: 0.62,
    height: 1.03,
    rotationZ: 0.012,
    matInset: 0.03,
    assetIds: ['poster-458'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-456',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #456',
    desc: 'The Charm Of Sports',
    x: 3.56,
    y: 3.98,
    width: 0.62,
    height: 1.03,
    rotationZ: 0.02,
    matInset: 0.03,
    assetIds: ['poster-456'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-454',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #454',
    desc: 'Fall in Love with Your Own Script',
    x: 6.78,
    y: 2.76,
    width: 0.62,
    height: 1.03,
    rotationZ: 0.014,
    matInset: 0.03,
    assetIds: ['poster-454'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-447',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #447',
    desc: 'LOVE & THE CITY - Dating & Relationships in Shenzhen',
    x: 5.02,
    y: 2.88,
    width: 0.62,
    height: 1.03,
    rotationZ: -0.016,
    matInset: 0.03,
    assetIds: ['poster-447'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-441',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #441',
    desc: 'Sharing Your Life Stories',
    x: 3.24,
    y: 2.68,
    width: 0.62,
    height: 1.03,
    rotationZ: 0.018,
    matInset: 0.03,
    assetIds: ['poster-441'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-440',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #440',
    desc: 'Warm Connections: Imagine, Then Soar',
    x: 7.02,
    y: 1.46,
    width: 0.62,
    height: 1.03,
    rotationZ: 0.016,
    matInset: 0.03,
    assetIds: ['poster-440'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-427',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #427',
    desc: 'Deep connections',
    x: 5.28,
    y: 1.58,
    width: 0.62,
    height: 1.03,
    rotationZ: -0.014,
    matInset: 0.03,
    assetIds: ['poster-427'],
    accent: '#b78b4f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-poster-428',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Meeting #428',
    desc: 'Trick, Treat, Toast',
    x: 3.52,
    y: 1.4,
    width: 0.62,
    height: 1.03,
    rotationZ: -0.018,
    matInset: 0.03,
    assetIds: ['poster-428'],
    accent: '#b78b4f',
    showPlaque: false,
  },
];

export const CLUB_INTRO_EXHIBIT_MAP = new Map(
  CLUB_INTRO_EXHIBITS.map(exhibit => [exhibit.id, exhibit] as const),
);

export const CLUB_INTRO_PRESENTATION_GROUPS: PresentationGroup[] = [
  {
    id: 'ti-speaking-wall',
    title: 'Toastmasters Meeting and Stage',
    roomIdx: 0,
    exhibitIds: [
      'ti-speaking-first-impression',
      'ti-speaking-2025-winners',
    ],
  },
  {
    id: 'ti-history-wall',
    title: 'Toastmasters History and Scale',
    roomIdx: 0,
    exhibitIds: [
      'ti-history-smedley',
      'ti-history-ymca',
      'ti-history-1924-meeting',
      'ti-world-map-wall',
    ],
  },
  {
    id: 'ti-keywords-wall',
    title: 'Toastmasters Three Keywords',
    roomIdx: 0,
    exhibitIds: [
      'ti-keyword-network',
      'ti-keyword-public-speaking',
      'ti-keyword-leadership',
    ],
  },
  {
    id: 'soarhigh-history-wall',
    title: 'SoarHigh History',
    roomIdx: 1,
    exhibitIds: [
      'soarhigh-history-airline',
      'soarhigh-history-meeting-04',
      'soarhigh-history-meeting-07',
      'soarhigh-history-full-english',
    ],
  },
  {
    id: 'soarhigh-keywords-wall',
    title: 'SoarHigh Three Keywords',
    roomIdx: 1,
    exhibitIds: [
      'soarhigh-family-photo-1',
      'soarhigh-family-photo-2',
      'soarhigh-family-photo-3',
      'soarhigh-family-photo-4',
      'soarhigh-fun-photo-1',
      'soarhigh-fun-photo-2',
      'soarhigh-fun-photo-3',
      'soarhigh-fun-photo-4',
      'soarhigh-fun-photo-5',
      'soarhigh-fun-photo-6',
      'soarhigh-fun-photo-7',
      'soarhigh-fun-photo-8',
      'soarhigh-growth-contest-2026',
    ],
  },
];

export const CLUB_INTRO_PRESENTATION_CUES: PresentationCue[] = [
  {
    id: 'ti-meeting-scene',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Toastmasters Meeting',
    desc: 'This is a common Toastmasters meeting scene: speaking, listening, and evaluation inside a structured, supportive room.',
    descSegments: [
      {text: 'A common Toastmasters meeting scene:'},
      {text: 'Speaking', tone: 'accent', bullet: true},
      {text: 'Listening', tone: 'accent', bullet: true},
      {text: 'Evaluation', tone: 'accent', bullet: true, breakAfter: true},
      {text: 'inside a ', breakAfter: false},
      {text: 'structured, supportive room', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'This is a common Toastmasters meeting scene. Members come together to practise speaking, listening, and giving evaluations in a structured, supportive room.',
    camera: {
      position: [3.72, 1.68, -7.35],
      lookAt: [8.5, 2.5, -7.75],
      durationMs: 1100,
    },
  },
  {
    id: 'ti-nonprofit-purpose',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Nonprofit for Growth',
    desc: 'Toastmasters is a nonprofit organization that helps members improve public speaking, communication, and leadership through practice.',
    descSegments: [
      {text: 'A '},
      {text: 'nonprofit organization', tone: 'strong'},
      {text: ' helping members improve:'},
      {text: 'Public speaking', tone: 'accent', bullet: true},
      {text: 'Communication', tone: 'accent', bullet: true},
      {text: 'Leadership', tone: 'accent', bullet: true, breakAfter: true},
      {text: ' through '},
      {text: 'practice', tone: 'italic'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is a nonprofit organization that helps its members improve public speaking, communication, and leadership skills through practice.',
    camera: {
      position: [3.72, 1.7, -6.9],
      lookAt: [8.5, 2.45, -7.45],
      durationMs: 650,
    },
  },
  {
    id: 'ti-contest-stage',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-2025-winners',
    title: 'Practice Becomes Stage',
    desc: 'Toastmasters also has speech contests. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    descSegments: [
      {text: 'Toastmasters also has '},
      {text: 'speech contests', tone: 'accent'},
      {text: '.'},
      {text: '2025 winners', tone: 'stat', bullet: true},
      {text: 'Regular practice grows into a ', bullet: true},
      {text: 'larger stage', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is also a stage for contests and recognition. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    camera: {
      position: [3.86, 1.72, -4.55],
      lookAt: [8.5, 2.42, -3.16],
      durationMs: 900,
    },
  },
  {
    id: 'ti-smedley-origin',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-smedley',
    title: 'Where It Began',
    desc: 'Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    descSegments: [
      {text: 'More than ', bullet: true},
      {text: '100 years', tone: 'stat'},
      {text: ' of history'},
      {text: 'Founded by ', bullet: true},
      {text: 'Ralph C. Smedley', tone: 'warm'},
      {text: 'Founded in ', bullet: true},
      {text: '1924', tone: 'stat'},
    ],
    spokenCue: 'You may wonder where Toastmasters came from. Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    camera: {
      position: [3.35, 1.72, -2.45],
      lookAt: [5.25, 2.42, 1.0],
      durationMs: 1250,
    },
  },
  {
    id: 'ti-ymca-roots',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-ymca',
    title: 'The Early Home',
    desc: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    descSegments: [
      {text: 'The early idea took shape in a '},
      {text: 'YMCA setting', tone: 'warm'},
      {text: '.'},
      {text: 'People gathered to practise ', bullet: true},
      {text: 'better communication', tone: 'accent'},
      {text: '.'},
    ],
    spokenCue: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    camera: {
      position: [1.0, 1.72, -2.15],
      lookAt: [1.05, 3.22, 1.0],
      durationMs: 850,
    },
  },
  {
    id: 'ti-early-meeting',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-1924-meeting',
    title: 'Early Club Meetings',
    desc: 'From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    descSegments: [
      {text: 'A simple learning model from the beginning:'},
      {text: 'Speak', tone: 'accent', bullet: true},
      {text: 'Listen', tone: 'accent', bullet: true},
      {text: 'Evaluate', tone: 'accent', bullet: true},
      {text: 'Try again', tone: 'italic', bullet: true},
    ],
    spokenCue: 'This is an early club meeting scene. From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    camera: {
      position: [0.65, 1.58, -2.05],
      lookAt: [0.55, 1.45, 1.0],
      durationMs: 750,
    },
  },
  {
    id: 'ti-global-scale',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-world-map-wall',
    title: 'A Global Network',
    desc: 'Today, Toastmasters has clubs in 140+ countries, with 15K+ clubs and 280K+ members. In Shenzhen, there are 90+ clubs.',
    descSegments: [
      {text: 'Today, Toastmasters reaches:'},
      {text: '140+ countries', tone: 'stat', bullet: true},
      {text: '15K+ clubs', tone: 'stat', bullet: true},
      {text: '280K+ members', tone: 'stat', bullet: true},
      {text: '90+ clubs in Shenzhen', tone: 'warm', bullet: true},
    ],
    spokenCue: 'Today, Toastmasters has clubs in more than 140 countries, with more than 15 thousand clubs and 280 thousand members. Just in Shenzhen, there are more than 90 clubs.',
    camera: {
      position: [-3.35, 1.7, -2.55],
      lookAt: [-4.15, 2.45, 1.0],
      durationMs: 950,
    },
  },
  {
    id: 'ti-keyword-network-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-network',
    title: 'Network',
    desc: 'Through the huge Toastmasters club network, members connect with people from all walks of life.',
    descSegments: [
      {text: 'First keyword: '},
      {text: 'Network', tone: 'accent', breakAfter: true},
      {text: 'Connect with people from ', bullet: true},
      {text: 'all walks of life', tone: 'warm'},
      {text: 'A huge club network creates chances to meet people you would not otherwise meet.', bullet: true},
      {text: 'Some members even met their second half through Toastmasters.', tone: 'italic', bullet: true},
    ],
    spokenCue: 'There are three keywords for Toastmasters. The first keyword is network. Through this huge club network, you have the chance to connect with people from all walks of life. Some members even met their second half through Toastmasters.',
    camera: {
      position: [-3.85, 1.75, -1.78],
      lookAt: [-8.5, 2.4, -1.76],
      durationMs: 1100,
    },
  },
  {
    id: 'ti-keyword-public-speaking-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-public-speaking',
    title: 'Public Speaking',
    desc: 'Members learn through practice to present and communicate better, making their voices more convincing and powerful.',
    descSegments: [
      {text: 'Second keyword: '},
      {text: 'Public Speaking', tone: 'accent', breakAfter: true},
      {text: 'Learn through ', bullet: true},
      {text: 'practice', tone: 'italic'},
      {text: 'Present and communicate better', tone: 'warm', bullet: true},
      {text: 'Make your voice more convincing and powerful', bullet: true},
    ],
    spokenCue: 'The second keyword is public speaking. Our members can learn through practice to present and communicate better, making their voices more convincing and powerful.',
    camera: {
      position: [-3.85, 1.78, -5.0],
      lookAt: [-8.5, 2.78, -5.0],
      durationMs: 850,
    },
  },
  {
    id: 'ti-keyword-leadership-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-leadership',
    title: 'Leadership',
    desc: 'By joining the club officer team and helping organize meetings and activities, members enhance leadership skills that can also advance their careers.',
    descSegments: [
      {text: 'Third keyword: '},
      {text: 'Leadership', tone: 'accent', breakAfter: true},
      {text: 'Join the club officers team', bullet: true},
      {text: 'Help organize meetings and activities', bullet: true},
      {text: 'Enhance leadership skills', tone: 'warm', bullet: true},
      {text: 'These skills have helped many members advance their careers.', tone: 'strong', bullet: true},
    ],
    spokenCue: 'The third keyword is leadership. By joining the club officers team to help organize meetings and activities, you can enhance your leadership skills. The skills gained in Toastmasters have helped many members advance their careers as well.',
    camera: {
      position: [-3.85, 1.75, -8.22],
      lookAt: [-8.5, 2.45, -8.24],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-airline-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-airline',
    title: 'Founded by Shenzhen Airline',
    desc: 'SoarHigh Toastmasters Club was established in 2014 by Shenzhen Airline as a corporate club.',
    descSegments: [
      {text: 'Established in ', bullet: true},
      {text: '2014', tone: 'stat'},
      {text: 'Founded by ', bullet: true},
      {text: 'Shenzhen Airline', tone: 'warm'},
      {text: 'Started as a ', bullet: true},
      {text: 'corporate club', tone: 'accent'},
    ],
    spokenCue: 'So our SoarHigh Toastmasters Club was established in 2014 by Shenzhen Airline as a corporate club.',
    camera: {
      position: [-3.85, 1.7, -18.55],
      lookAt: [-8.5, 2.32, -18.55],
      durationMs: 1200,
    },
  },
  {
    id: 'soarhigh-history-meeting-04-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-meeting-04',
    title: 'Early Meetings',
    desc: 'The early meetings helped shape SoarHigh from a company club into a wider community.',
    descSegments: [
      {text: 'Meeting #4', tone: 'accent', breakAfter: true},
      {text: 'A young club taking shape', bullet: true},
      {text: 'Members learning through regular meetings', bullet: true},
    ],
    spokenCue: 'These early meeting photos show how the club started to take shape through regular meetings and member participation.',
    camera: {
      position: [-3.85, 1.8, -21.85],
      lookAt: [-8.5, 3.26, -21.85],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-meeting-07-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-meeting-07',
    title: 'From Corporate to Public',
    desc: 'Two years later, SoarHigh turned into a public club that everyone can join.',
    descSegments: [
      {text: 'Two years later', tone: 'warm', breakAfter: true},
      {text: 'Turned into a ', bullet: true},
      {text: 'public club', tone: 'accent'},
      {text: 'Open to everyone who wants to join', bullet: true},
    ],
    spokenCue: 'Two years later, it turned into a public club that everyone can join.',
    camera: {
      position: [-3.85, 1.58, -22.15],
      lookAt: [-8.5, 1.5, -22.15],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-full-english-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-full-english',
    title: 'Full English Speaking Club',
    desc: "In 2024, SoarHigh decided to become a full English-speaking club. Today it remains the only English-speaking club in Bao'an district.",
    descSegments: [
      {text: 'In ', bullet: true},
      {text: '2024', tone: 'stat'},
      {text: ', SoarHigh decided to become a full English-speaking club.'},
      {text: "Bao'an district's only English-speaking club", tone: 'warm', bullet: true},
      {text: 'SoarHigh, so high, take me fly!', tone: 'strong', bullet: true},
    ],
    spokenCue: 'And in 2024, we decided to become a full English speaking club. Now we remain the only English speaking club in Baoan district. Our slogan is SoarHigh, so high, take me fly.',
    camera: {
      position: [-3.85, 1.84, -25.45],
      lookAt: [-8.5, 2.68, -25.45],
      durationMs: 950,
    },
  },
  {
    id: 'soarhigh-keyword-family-cue',
    groupId: 'soarhigh-keywords-wall',
    exhibitId: 'soarhigh-family-photo-1',
    title: 'Family Atmosphere',
    desc: 'Here in SoarHigh, we also have three keywords. The first is family atmosphere: we are more than Toastmasters, we are a family, to love, to care, to laugh, and to inspire.',
    descSegments: [
      {text: 'SoarHigh also has three keywords.', breakAfter: true},
      {text: 'First keyword: '},
      {text: 'Family Atmosphere', tone: 'accent', breakAfter: true},
      {text: 'More than Toastmasters', tone: 'warm', bullet: true},
      {text: 'We are a family', tone: 'strong', bullet: true},
      {text: 'To love, to care, to laugh, and to inspire', tone: 'italic', bullet: true},
    ],
    spokenCue: 'Here in SoarHigh, we also have three keywords. The first is family atmosphere. We are more than Toastmasters, we are a family, to love, to care, to laugh, and to inspire.',
    camera: {
      position: [-4.72, 1.8, -24.1],
      lookAt: [-4.92, 2.62, -28.5],
      durationMs: 1150,
    },
  },
  {
    id: 'soarhigh-keyword-fun-cue',
    groupId: 'soarhigh-keywords-wall',
    exhibitId: 'soarhigh-fun-photo-1',
    title: 'Fun Events',
    desc: 'Second is fun: other than outing events every month, SoarHigh has hosted many special fun meetings before, like speed dating and Halloween parties. You can visit soarhigh.top or the mini app 搜嗨头马 to know more about past meetings and events.',
    descSegments: [
      {text: 'Second keyword: '},
      {text: 'Fun', tone: 'accent', breakAfter: true},
      {text: 'Monthly outing events', tone: 'warm', bullet: true},
      {text: 'Special fun meetings: speed dating, Halloween parties, and more', tone: 'strong', bullet: true},
      {text: 'Website: soarhigh.top', tone: 'italic', bullet: true},
      {text: 'Mini app: 搜嗨头马', tone: 'italic', bullet: true},
    ],
    spokenCue: 'Second is fun. Other than outing events every month, we have hosted many special fun meetings before like speed dating, Halloween parties, et cetera. You can go to visit our website soarhigh dot top or our mini app 搜嗨头马 to know more about our past meetings and events.',
    camera: {
      position: [0.36, 1.8, -24.1],
      lookAt: [0.18, 2.7, -28.5],
      durationMs: 950,
    },
  },
  {
    id: 'soarhigh-keyword-growth-cue',
    groupId: 'soarhigh-keywords-wall',
    exhibitId: 'soarhigh-growth-contest-2026',
    title: 'Growth Through Contests',
    desc: 'Third is growth. Members grow by practising, receiving feedback, and challenging themselves on bigger stages. In 2026, SoarHigh members won first place in the Central Division Prepared Speech Evaluation Contest and second place in the Central Division International Speech Contest.',
    descSegments: [
      {text: 'Third keyword: '},
      {text: 'Growth', tone: 'accent', breakAfter: true},
      {text: 'Practice, feedback, and bigger stages', tone: 'warm', bullet: true},
      {text: '2026 Central Division Prepared Speech Evaluation: ', bullet: true},
      {text: '1st place', tone: 'stat'},
      {text: '2026 Central Division International Speech Contest: ', bullet: true},
      {text: '2nd place', tone: 'stat'},
    ],
    spokenCue: 'The third keyword is growth. Members grow by practising, receiving feedback, and challenging themselves on bigger stages. In 2026, SoarHigh members won first place in the Central Division Prepared Speech Evaluation Contest and second place in the Central Division International Speech Contest.',
    camera: {
      position: [4.7, 1.82, -24.08],
      lookAt: [5.42, 2.62, -28.5],
      durationMs: 950,
    },
  },
];
