import type { ClubIntroAsset, ExhibitData, PresentationCue, PresentationGroup } from './types';

export const CLUB_INTRO_ASSETS: ClubIntroAsset[] = [
  {
    id: 'ti-smedley',
    kind: 'photo',
    title: 'Ralph C. Smedley',
    role: 'toastmasters-scale',
    aspect: 606 / 663,
    localPath: '/assets/club-intro/ti-smedley.png',
    caption: 'Ralph C. Smedley, founder of Toastmasters.',
  },
  {
    id: 'ti-ymca-building',
    kind: 'photo',
    title: 'YMCA roots',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-ymca-building.png',
    caption: 'The YMCA setting where the early Toastmasters idea took shape.',
  },
  {
    id: 'ti-1924-club-meeting',
    kind: 'photo',
    title: '1924 club meeting',
    role: 'toastmasters-scale',
    aspect: 1660 / 700,
    localPath: '/assets/club-intro/ti-1924-club-meeting.png',
    caption: 'An early Toastmasters club meeting scene.',
  },
  {
    id: 'ti-world-map',
    kind: 'photo',
    title: 'Toastmasters around the world',
    role: 'toastmasters-scale',
    aspect: 1672 / 941,
    localPath: '/assets/club-intro/ti-world-map.png',
    caption: 'Toastmasters has clubs across a global learning network.',
  },
  {
    id: 'ti-past-international-presidents',
    kind: 'photo',
    title: 'Past International Presidents',
    role: 'toastmasters-scale',
    aspect: 1000 / 663,
    localPath: '/assets/club-intro/ti-past-international-presidents.png',
    caption: "Past Toastmasters International presidents gathered in 2024 to celebrate Toastmasters' 100th anniversary.",
  },
  {
    id: 'ti-networking',
    kind: 'photo',
    title: 'Networking',
    role: 'network',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/ti-networking.jpg',
    caption: 'Members expand opportunities by connecting across a wider learning network.',
  },
  {
    id: 'ti-public-speaking',
    kind: 'photo',
    title: 'Public Speaking',
    role: 'public-speaking',
    aspect: 1,
    localPath: '/assets/club-intro/ti-public-speaking.jpg',
    caption: 'Practice in front of an audience turns communication into confidence.',
  },
  {
    id: 'ti-leadership',
    kind: 'photo',
    title: 'Leadership',
    role: 'leadership',
    aspect: 1706 / 1279,
    localPath: '/assets/club-intro/ti-leadership.jpg',
    caption: 'Club roles and shared responsibility give members practical leadership experience.',
  },
  {
    id: 'ti-first-impression',
    kind: 'photo',
    title: 'First Impression',
    role: 'public-speaking',
    aspect: 941 / 1672,
    localPath: '/assets/club-intro/ti-first-impression.png',
    caption: 'A stage moment where a first impression matters.',
  },
  {
    id: 'ti-2025-winners',
    kind: 'photo',
    title: '2025 winners',
    role: 'public-speaking',
    aspect: 1000 / 663,
    localPath: '/assets/club-intro/ti-2025-winners.jpg',
    caption: 'Speech contests and recognition turn practice into public achievement.',
  },
  {
    id: 'ti-2026-118-guangfo',
    kind: 'photo',
    title: '2026 District 118 Guangzhou-Foshan Summit',
    role: 'network',
    aspect: 2000 / 1125,
    localPath: '/assets/club-intro/ti-2026-118-guangfo.jpg',
    caption: 'A moment from the 2026 District 118 Guangzhou-Foshan summit.',
  },
  {
    id: 'network-member-day',
    kind: 'poster',
    title: 'Member Day connections',
    role: 'network',
    aspect: 0.563,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/6fe004c1-1891-4e1e-9ea8-069f0226069b/media/1000046777.jpg',
    localPath: '/assets/club-intro/member-day.jpg',
    meetingTheme: 'SoarHigh Member Day',
    caption: 'Members and guests meet through SoarHigh activities.',
  },
  {
    id: 'speaking-workshop',
    kind: 'photo',
    title: 'Learning by doing',
    role: 'public-speaking',
    aspect: 0.75,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047516.jpg',
    localPath: '/assets/club-intro/public-speaking-workshop.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'Members practise speaking, facilitation, and prepared sharing.',
  },
  {
    id: 'speaking-debate',
    kind: 'photo',
    title: 'Debate Arena',
    role: 'public-speaking',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047519.jpg',
    localPath: '/assets/club-intro/debate-arena.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'A live format for fast, clear, persuasive communication.',
  },
  {
    id: 'leadership-election',
    kind: 'photo',
    title: 'Club officers election',
    role: 'leadership',
    aspect: 2.17,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/7eaad288-10b1-475a-b82b-8fb0c8122511/media/1000047084.jpg',
    localPath: '/assets/club-intro/officer-election.jpg',
    meetingNo: 457,
    meetingTheme: '23rd Club Officers Election',
    caption: 'Club officers learn leadership by organizing real meetings.',
  },
  {
    id: 'soarhigh-ai-poster',
    kind: 'poster',
    title: 'A recent SoarHigh meeting',
    role: 'soarhigh-history',
    aspect: 0.562,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047095.jpg',
    localPath: '/assets/club-intro/ai-poster.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'A recent English meeting poster from the SoarHigh website.',
  },
  {
    id: 'soarhigh-shenzhen-airline',
    kind: 'photo',
    title: 'Shenzhen Airline',
    role: 'soarhigh-history',
    aspect: 4846 / 3231,
    localPath: '/assets/club-intro/shenzhen-airline.jpeg',
    caption: 'SoarHigh was established by Shenzhen Airline in 2014 as a corporate club.',
  },
  {
    id: 'soarhigh-meeting-04',
    kind: 'photo',
    title: 'Meeting #4',
    role: 'soarhigh-history',
    aspect: 839 / 462,
    localPath: '/assets/club-intro/meeting-04.jpg',
    meetingNo: 4,
    caption: 'An early SoarHigh club meeting.',
  },
  {
    id: 'soarhigh-meeting-07',
    kind: 'photo',
    title: 'Meeting #7',
    role: 'soarhigh-history',
    aspect: 697 / 442,
    localPath: '/assets/club-intro/meeting-07.jpg',
    meetingNo: 7,
    caption: 'Another early SoarHigh club meeting as the club grew.',
  },
  {
    id: 'soarhigh-2024-full-english',
    kind: 'photo',
    title: 'Full English Club',
    role: 'soarhigh-history',
    aspect: 1620 / 1080,
    localPath: '/assets/club-intro/2024-full-english.jpg',
    meetingTheme: 'Full English Speaking Club',
    caption: 'In 2024, SoarHigh decided to become a full English-speaking club.',
  },
  {
    id: 'meeting-458-guest-introduction',
    kind: 'photo',
    title: 'Guest Introduction',
    role: 'ordinary-photo',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/573e97b3-ad69-4fe7-ad77-8905159095f2/media/1000047522.jpg',
    localPath: '/assets/club-intro/meeting-458-guest-introduction.jpg',
    meetingNo: 458,
    meetingTheme: 'AI Boom or AI Doom',
    caption: 'Guest Introduction group photo.',
  },
  {
    id: 'meeting-455-about-childhood',
    kind: 'photo',
    title: 'About Childhood',
    role: 'ordinary-photo',
    aspect: 1702 / 1276,
    localPath: '/assets/club-intro/meeting-455-about-childhood.jpg',
    meetingNo: 455,
    meetingTheme: 'About Childhood',
    caption: 'A photo from this meeting.',
  },
  {
    id: 'fun-halloween',
    kind: 'photo',
    title: 'Halloween special meeting',
    role: 'fun',
    aspect: 1.334,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/5cd74e63-4b9d-4c51-8a66-a2e90696ebf4/media/1000037798.jpg',
    localPath: '/assets/club-intro/halloween.jpg',
    meetingTheme: 'Halloween Trick Treat Toast',
    caption: 'SoarHigh has hosted many special themed meetings.',
  },
  {
    id: 'fun-christmas',
    kind: 'poster',
    title: 'Christmas dinner party',
    role: 'fun',
    aspect: 0.749,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/ce0a4299-b5de-4ed3-aa13-bb03ade5dff7/media/1000040992.jpg',
    localPath: '/assets/club-intro/christmas.jpg',
    meetingTheme: 'Christmas Eve Dinner Party',
    caption: 'Events outside the regular meeting keep the club lively.',
  },
  {
    id: 'growth-evaluation',
    kind: 'photo',
    title: 'Evaluation workshop',
    role: 'growth',
    aspect: 0.75,
    sourceUrl: 'https://soarhigh.oss-cn-shenzhen.aliyuncs.com/public/meetings/7dbf1542-b26d-4fb5-889f-19feb2bebeb8/media/1000045464.jpg',
    localPath: '/assets/club-intro/evaluation-workshop.png',
    meetingNo: 452,
    meetingTheme: 'Power Up Your Evaluation',
    caption: 'Growth happens through practice, feedback, and another try.',
  },
  {
    id: 'soarhigh-link',
    kind: 'qr',
    title: 'soarhigh.top',
    role: 'final-cta',
    caption: 'Website, mini app, and meeting archive.',
  },
];

export const CLUB_INTRO_ASSET_MAP = new Map(
  CLUB_INTRO_ASSETS.map(asset => [asset.id, asset] as const),
);

export const CLUB_INTRO_EXHIBITS: ExhibitData[] = [
  {
    id: 'ti-history-smedley',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Ralph C. Smedley',
    desc: 'Ralph C. Smedley founded Toastmasters and shaped its early learning culture.',
    x: 5.25,
    y: 2.42,
    width: 2.4,
    height: 2.6,
    assetIds: ['ti-smedley'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-ymca',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'YMCA Roots',
    desc: 'The YMCA setting where the early Toastmasters idea took shape.',
    x: 1.05,
    y: 3.36,
    width: 3.05,
    height: 1.45,
    rotationZ: 0.02,
    assetIds: ['ti-ymca-building'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-history-1924-meeting',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: '1924 Club Meeting',
    desc: 'An early Toastmasters club meeting scene.',
    x: 0.55,
    y: 1.42,
    width: 3.15,
    height: 1.45,
    rotationZ: -0.017,
    assetIds: ['ti-1924-club-meeting'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-world-map-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'front',
    title: 'Global Toastmasters Network',
    desc: 'Toastmasters clubs connect members across more than 140 countries.',
    x: -4.15,
    y: 2.5,
    width: 4.05,
    height: 2.28,
    assetIds: ['ti-world-map'],
    lines: ['140+ countries', '15k+ clubs', '280k+ members', '90+ Shenzhen clubs'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-network',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Network',
    desc: 'A huge club network gives members chances to connect with people from all walks of life.',
    z: 3.24,
    y: 2.4,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-networking'],
    accent: '#0582ca',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-public-speaking',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Public Speaking',
    desc: 'Members learn through practice to present and communicate with more confidence.',
    z: 0,
    y: 2.79,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-public-speaking'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-keyword-leadership',
    kind: 'circle-photo',
    roomIdx: 0,
    wall: 'left',
    title: 'Leadership',
    desc: 'Club officer roles and activities help members grow practical leadership skills.',
    z: -3.24,
    y: 2.45,
    width: 2.38,
    height: 2.38,
    assetIds: ['ti-leadership'],
    accent: '#8e44ad',
    showPlaque: false,
  },
  {
    id: 'ti-speaking-first-impression',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: 'First Impression',
    desc: 'A stage moment where a first impression matters.',
    z: -2.75,
    y: 2.52,
    width: 1.72,
    height: 2.94,
    assetIds: ['ti-first-impression'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-speaking-2025-winners',
    kind: 'photo',
    roomIdx: 0,
    wall: 'right',
    title: '2025 Winners',
    desc: 'Speech contests and recognition turn practice into public achievement.',
    z: 1.84,
    y: 2.52,
    width: 3.55,
    height: 2.46,
    assetIds: ['ti-2025-winners'],
    accent: '#8fd14f',
    showPlaque: false,
  },
  {
    id: 'ti-2026-118-guangfo-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'back',
    title: '2026 District 118 Guangzhou-Foshan Summit',
    desc: 'A 2026 District 118 Guangzhou-Foshan summit moment.',
    x: -5.12,
    y: 2.35,
    width: 3.55,
    height: 2.1,
    assetIds: ['ti-2026-118-guangfo'],
    accent: '#c9a96e',
    showPlaque: false,
  },
  {
    id: 'ti-past-international-presidents-wall',
    kind: 'photo',
    roomIdx: 0,
    wall: 'back',
    title: 'Past International Presidents',
    desc: "Past Toastmasters International presidents gathered in 2024 to celebrate Toastmasters' 100th anniversary.",
    x: 5.12,
    y: 2.36,
    width: 3.45,
    height: 2.25,
    assetIds: ['ti-past-international-presidents'],
    accent: '#0f8fcf',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-airline',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Shenzhen Airline',
    desc: 'SoarHigh was established in 2014 by Shenzhen Airline as a corporate club.',
    z: 3.45,
    y: 2.32,
    width: 2.55,
    height: 1.7,
    assetIds: ['soarhigh-shenzhen-airline'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-meeting-04',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Meeting #4',
    desc: 'An early SoarHigh meeting from the first chapter of the club.',
    z: 0.15,
    y: 3.26,
    width: 2.31,
    height: 1.36,
    assetIds: ['soarhigh-meeting-04'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-meeting-07',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Meeting #7',
    desc: 'Another early SoarHigh meeting as the club community developed.',
    z: -0.15,
    y: 1.5,
    width: 2.03,
    height: 1.36,
    assetIds: ['soarhigh-meeting-07'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-history-full-english',
    kind: 'photo',
    roomIdx: 1,
    wall: 'left',
    title: 'Full English Club',
    desc: "In 2024, SoarHigh decided to become a full English-speaking club and remains Bao'an district's only English-speaking club.",
    z: -3.45,
    y: 2.68,
    width: 2.55,
    height: 1.7,
    assetIds: ['soarhigh-2024-full-english'],
    accent: '#ff8a2a',
    showPlaque: false,
  },
  {
    id: 'soarhigh-slogan',
    kind: 'slogan',
    roomIdx: 1,
    wall: 'back',
    title: 'Soarhigh So High',
    desc: 'Take me fly!',
    x: -3.3,
    y: 3.1,
    width: 5.2,
    height: 1.25,
    lines: ['Soarhigh So High', 'Take Me Fly'],
    accent: '#ffd166',
  },
  {
    id: 'soarhigh-family',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'right',
    title: 'Family Atmosphere',
    desc: 'More than Toastmasters: a family to love, care, laugh, and inspire.',
    z: -4.15,
    y: 2.25,
    width: 3.45,
    height: 2.35,
    lines: ['Love', 'Care', 'Laugh', 'Inspire'],
    accent: '#4f7bd9',
  },
  {
    id: 'soarhigh-fun',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'right',
    title: 'Fun Events',
    desc: 'Outings, theme nights, parties, and creative special meetings keep the club alive.',
    z: -0.25,
    y: 2.25,
    width: 3.45,
    height: 2.35,
    assetIds: ['fun-halloween'],
    lines: ['Outings', 'Halloween', 'Christmas', 'Special meetings'],
    accent: '#ef476f',
  },
  {
    id: 'soarhigh-christmas-party',
    kind: 'photo',
    roomIdx: 1,
    wall: 'right',
    title: 'Christmas Party',
    desc: 'Theme meetings and parties make SoarHigh feel lively and memorable.',
    z: 2.1,
    y: 2.25,
    width: 1.6,
    height: 2.65,
    assetIds: ['fun-christmas'],
    accent: '#ef476f',
    showPlaque: false,
  },
  {
    id: 'soarhigh-growth',
    kind: 'keyword',
    roomIdx: 1,
    wall: 'front',
    title: 'Growth',
    desc: 'SoarHigh is a stage to test imperfect ideas, see real changes, and feel the happiness from growth.',
    x: 4.15,
    y: 2.25,
    width: 2.45,
    height: 3.0,
    assetIds: ['speaking-workshop'],
    lines: ['Try', 'Feedback', 'Change', 'Grow'],
    accent: '#2ec4b6',
  },
  {
    id: 'soarhigh-ambient-evaluation',
    kind: 'photo',
    roomIdx: 1,
    wall: 'front',
    title: 'Feedback and Evaluation',
    desc: 'A supporting SoarHigh photo about learning through feedback.',
    x: -4.15,
    y: 2.25,
    width: 2.05,
    height: 2.7,
    assetIds: ['growth-evaluation'],
    accent: '#ffd166',
    showPlaque: false,
  },
  {
    id: 'soarhigh-cta',
    kind: 'qr',
    roomIdx: 1,
    wall: 'back',
    title: 'Visit SoarHigh',
    desc: 'Website: soarhigh.top. Mini app: 搜嗨头马.',
    x: 4.25,
    y: 2.35,
    width: 3.2,
    height: 2.0,
    assetIds: ['soarhigh-link'],
    lines: ['www.soarhigh.top', 'Mini app: 搜嗨头马', 'Photos, posts, meetings'],
    accent: '#2bb673',
  },
];

export const CLUB_INTRO_EXHIBIT_MAP = new Map(
  CLUB_INTRO_EXHIBITS.map(exhibit => [exhibit.id, exhibit] as const),
);

export const CLUB_INTRO_PRESENTATION_GROUPS: PresentationGroup[] = [
  {
    id: 'ti-speaking-wall',
    title: 'Toastmasters Meeting and Stage',
    roomIdx: 0,
    exhibitIds: [
      'ti-speaking-first-impression',
      'ti-speaking-2025-winners',
    ],
  },
  {
    id: 'ti-history-wall',
    title: 'Toastmasters History and Scale',
    roomIdx: 0,
    exhibitIds: [
      'ti-history-smedley',
      'ti-history-ymca',
      'ti-history-1924-meeting',
      'ti-world-map-wall',
    ],
  },
  {
    id: 'ti-keywords-wall',
    title: 'Toastmasters Three Keywords',
    roomIdx: 0,
    exhibitIds: [
      'ti-keyword-network',
      'ti-keyword-public-speaking',
      'ti-keyword-leadership',
    ],
  },
  {
    id: 'soarhigh-history-wall',
    title: 'SoarHigh History',
    roomIdx: 1,
    exhibitIds: [
      'soarhigh-history-airline',
      'soarhigh-history-meeting-04',
      'soarhigh-history-meeting-07',
      'soarhigh-history-full-english',
    ],
  },
];

export const CLUB_INTRO_PRESENTATION_CUES: PresentationCue[] = [
  {
    id: 'ti-meeting-scene',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Toastmasters Meeting',
    desc: 'This is a common Toastmasters meeting scene: speaking, listening, and evaluation inside a structured, supportive room.',
    descSegments: [
      {text: 'A common Toastmasters meeting scene:'},
      {text: 'Speaking', tone: 'accent', bullet: true},
      {text: 'Listening', tone: 'accent', bullet: true},
      {text: 'Evaluation', tone: 'accent', bullet: true, breakAfter: true},
      {text: 'inside a ', breakAfter: false},
      {text: 'structured, supportive room', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'This is a common Toastmasters meeting scene. Members come together to practise speaking, listening, and giving evaluations in a structured, supportive room.',
    camera: {
      position: [3.72, 1.68, -7.35],
      lookAt: [8.5, 2.5, -7.75],
      durationMs: 1100,
    },
  },
  {
    id: 'ti-nonprofit-purpose',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-first-impression',
    title: 'A Nonprofit for Growth',
    desc: 'Toastmasters is a nonprofit organization that helps members improve public speaking, communication, and leadership through practice.',
    descSegments: [
      {text: 'A '},
      {text: 'nonprofit organization', tone: 'strong'},
      {text: ' helping members improve:'},
      {text: 'Public speaking', tone: 'accent', bullet: true},
      {text: 'Communication', tone: 'accent', bullet: true},
      {text: 'Leadership', tone: 'accent', bullet: true, breakAfter: true},
      {text: ' through '},
      {text: 'practice', tone: 'italic'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is a nonprofit organization that helps its members improve public speaking, communication, and leadership skills through practice.',
    camera: {
      position: [3.72, 1.7, -6.9],
      lookAt: [8.5, 2.45, -7.45],
      durationMs: 650,
    },
  },
  {
    id: 'ti-contest-stage',
    groupId: 'ti-speaking-wall',
    exhibitId: 'ti-speaking-2025-winners',
    title: 'Practice Becomes Stage',
    desc: 'Toastmasters also has speech contests. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    descSegments: [
      {text: 'Toastmasters also has '},
      {text: 'speech contests', tone: 'accent'},
      {text: '.'},
      {text: '2025 winners', tone: 'stat', bullet: true},
      {text: 'Regular practice grows into a ', bullet: true},
      {text: 'larger stage', tone: 'warm'},
      {text: '.'},
    ],
    spokenCue: 'Toastmasters is also a stage for contests and recognition. These are the 2025 winners, showing how regular practice can grow into a larger stage.',
    camera: {
      position: [3.86, 1.72, -4.55],
      lookAt: [8.5, 2.42, -3.16],
      durationMs: 900,
    },
  },
  {
    id: 'ti-smedley-origin',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-smedley',
    title: 'Where It Began',
    desc: 'Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    descSegments: [
      {text: 'More than ', bullet: true},
      {text: '100 years', tone: 'stat'},
      {text: ' of history'},
      {text: 'Founded by ', bullet: true},
      {text: 'Ralph C. Smedley', tone: 'warm'},
      {text: 'Founded in ', bullet: true},
      {text: '1924', tone: 'stat'},
    ],
    spokenCue: 'You may wonder where Toastmasters came from. Toastmasters has more than 100 years of history. It was founded by Ralph C. Smedley in 1924.',
    camera: {
      position: [3.35, 1.72, -2.45],
      lookAt: [5.25, 2.42, 1.0],
      durationMs: 1250,
    },
  },
  {
    id: 'ti-ymca-roots',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-ymca',
    title: 'The Early Home',
    desc: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    descSegments: [
      {text: 'The early idea took shape in a '},
      {text: 'YMCA setting', tone: 'warm'},
      {text: '.'},
      {text: 'People gathered to practise ', bullet: true},
      {text: 'better communication', tone: 'accent'},
      {text: '.'},
    ],
    spokenCue: 'The early Toastmasters idea took shape in a YMCA setting, where people gathered to practise better communication.',
    camera: {
      position: [1.0, 1.72, -2.15],
      lookAt: [1.05, 3.22, 1.0],
      durationMs: 850,
    },
  },
  {
    id: 'ti-early-meeting',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-history-1924-meeting',
    title: 'Early Club Meetings',
    desc: 'From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    descSegments: [
      {text: 'A simple learning model from the beginning:'},
      {text: 'Speak', tone: 'accent', bullet: true},
      {text: 'Listen', tone: 'accent', bullet: true},
      {text: 'Evaluate', tone: 'accent', bullet: true},
      {text: 'Try again', tone: 'italic', bullet: true},
    ],
    spokenCue: 'This is an early club meeting scene. From the beginning, the learning model was simple and powerful: speak, listen, evaluate, and try again.',
    camera: {
      position: [0.65, 1.58, -2.05],
      lookAt: [0.55, 1.45, 1.0],
      durationMs: 750,
    },
  },
  {
    id: 'ti-global-scale',
    groupId: 'ti-history-wall',
    exhibitId: 'ti-world-map-wall',
    title: 'A Global Network',
    desc: 'Today, Toastmasters has clubs in 140+ countries, with 15K+ clubs and 280K+ members. In Shenzhen, there are 90+ clubs.',
    descSegments: [
      {text: 'Today, Toastmasters reaches:'},
      {text: '140+ countries', tone: 'stat', bullet: true},
      {text: '15K+ clubs', tone: 'stat', bullet: true},
      {text: '280K+ members', tone: 'stat', bullet: true},
      {text: '90+ clubs in Shenzhen', tone: 'warm', bullet: true},
    ],
    spokenCue: 'Today, Toastmasters has clubs in more than 140 countries, with more than 15 thousand clubs and 280 thousand members. Just in Shenzhen, there are more than 90 clubs.',
    camera: {
      position: [-3.35, 1.7, -2.55],
      lookAt: [-4.15, 2.45, 1.0],
      durationMs: 950,
    },
  },
  {
    id: 'ti-keyword-network-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-network',
    title: 'Network',
    desc: 'Through the huge Toastmasters club network, members connect with people from all walks of life.',
    descSegments: [
      {text: 'First keyword: '},
      {text: 'Network', tone: 'accent', breakAfter: true},
      {text: 'Connect with people from ', bullet: true},
      {text: 'all walks of life', tone: 'warm'},
      {text: 'A huge club network creates chances to meet people you would not otherwise meet.', bullet: true},
      {text: 'Some members even met their second half through Toastmasters.', tone: 'italic', bullet: true},
    ],
    spokenCue: 'There are three keywords for Toastmasters. The first keyword is network. Through this huge club network, you have the chance to connect with people from all walks of life. Some members even met their second half through Toastmasters.',
    camera: {
      position: [-3.85, 1.75, -1.78],
      lookAt: [-8.5, 2.4, -1.76],
      durationMs: 1100,
    },
  },
  {
    id: 'ti-keyword-public-speaking-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-public-speaking',
    title: 'Public Speaking',
    desc: 'Members learn through practice to present and communicate better, making their voices more convincing and powerful.',
    descSegments: [
      {text: 'Second keyword: '},
      {text: 'Public Speaking', tone: 'accent', breakAfter: true},
      {text: 'Learn through ', bullet: true},
      {text: 'practice', tone: 'italic'},
      {text: 'Present and communicate better', tone: 'warm', bullet: true},
      {text: 'Make your voice more convincing and powerful', bullet: true},
    ],
    spokenCue: 'The second keyword is public speaking. Our members can learn through practice to present and communicate better, making their voices more convincing and powerful.',
    camera: {
      position: [-3.85, 1.78, -5.0],
      lookAt: [-8.5, 2.78, -5.0],
      durationMs: 850,
    },
  },
  {
    id: 'ti-keyword-leadership-cue',
    groupId: 'ti-keywords-wall',
    exhibitId: 'ti-keyword-leadership',
    title: 'Leadership',
    desc: 'By joining the club officer team and helping organize meetings and activities, members enhance leadership skills that can also advance their careers.',
    descSegments: [
      {text: 'Third keyword: '},
      {text: 'Leadership', tone: 'accent', breakAfter: true},
      {text: 'Join the club officers team', bullet: true},
      {text: 'Help organize meetings and activities', bullet: true},
      {text: 'Enhance leadership skills', tone: 'warm', bullet: true},
      {text: 'These skills have helped many members advance their careers.', tone: 'strong', bullet: true},
    ],
    spokenCue: 'The third keyword is leadership. By joining the club officers team to help organize meetings and activities, you can enhance your leadership skills. The skills gained in Toastmasters have helped many members advance their careers as well.',
    camera: {
      position: [-3.85, 1.75, -8.22],
      lookAt: [-8.5, 2.45, -8.24],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-airline-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-airline',
    title: 'Founded by Shenzhen Airline',
    desc: 'SoarHigh Toastmasters Club was established in 2014 by Shenzhen Airline as a corporate club.',
    descSegments: [
      {text: 'Established in ', bullet: true},
      {text: '2014', tone: 'stat'},
      {text: 'Founded by ', bullet: true},
      {text: 'Shenzhen Airline', tone: 'warm'},
      {text: 'Started as a ', bullet: true},
      {text: 'corporate club', tone: 'accent'},
    ],
    spokenCue: 'So our SoarHigh Toastmasters Club was established in 2014 by Shenzhen Airline as a corporate club.',
    camera: {
      position: [-3.85, 1.7, -18.55],
      lookAt: [-8.5, 2.32, -18.55],
      durationMs: 1200,
    },
  },
  {
    id: 'soarhigh-history-meeting-04-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-meeting-04',
    title: 'Early Meetings',
    desc: 'The early meetings helped shape SoarHigh from a company club into a wider community.',
    descSegments: [
      {text: 'Meeting #4', tone: 'accent', breakAfter: true},
      {text: 'A young club taking shape', bullet: true},
      {text: 'Members learning through regular meetings', bullet: true},
    ],
    spokenCue: 'These early meeting photos show how the club started to take shape through regular meetings and member participation.',
    camera: {
      position: [-3.85, 1.8, -21.85],
      lookAt: [-8.5, 3.26, -21.85],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-meeting-07-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-meeting-07',
    title: 'From Corporate to Public',
    desc: 'Two years later, SoarHigh turned into a public club that everyone can join.',
    descSegments: [
      {text: 'Two years later', tone: 'warm', breakAfter: true},
      {text: 'Turned into a ', bullet: true},
      {text: 'public club', tone: 'accent'},
      {text: 'Open to everyone who wants to join', bullet: true},
    ],
    spokenCue: 'Two years later, it turned into a public club that everyone can join.',
    camera: {
      position: [-3.85, 1.58, -22.15],
      lookAt: [-8.5, 1.5, -22.15],
      durationMs: 850,
    },
  },
  {
    id: 'soarhigh-history-full-english-cue',
    groupId: 'soarhigh-history-wall',
    exhibitId: 'soarhigh-history-full-english',
    title: 'Full English Speaking Club',
    desc: "In 2024, SoarHigh decided to become a full English-speaking club. Today it remains the only English-speaking club in Bao'an district.",
    descSegments: [
      {text: 'In ', bullet: true},
      {text: '2024', tone: 'stat'},
      {text: ', SoarHigh decided to become a full English-speaking club.'},
      {text: "Bao'an district's only English-speaking club", tone: 'warm', bullet: true},
      {text: 'SoarHigh, so high, take me fly!', tone: 'strong', bullet: true},
    ],
    spokenCue: 'And in 2024, we decided to become a full English speaking club. Now we remain the only English speaking club in Baoan district. Our slogan is SoarHigh, so high, take me fly.',
    camera: {
      position: [-3.85, 1.84, -25.45],
      lookAt: [-8.5, 2.68, -25.45],
      durationMs: 950,
    },
  },
];
